### ISSUE TITLE
Build manually Error !!!

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#110]
Dear Mosajjal,

Error During Installation:-

[root@Home-Server tmp]# cd
[root@Home-Server ~]# git clone https://github.com/mosajjal/dnsmonster --depth 1 /tmp/dnsmonster
Cloning into '/tmp/dnsmonster'...
remote: Enumerating objects: 209, done.
remote: Counting objects: 100% (209/209), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 209 (delta 21), reused 146 (delta 9), pack-reused 0
Receiving objects: 100% (209/209), 3.90 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (21/21), done.
[root@Home-Server ~]# cd /tmp/dnsmonster
[root@Home-Server dnsmonster]# go get
### **go: no package to get in current directory**
[root@Home-Server dnsmonster]# go build -o dnsmonster .
no Go files in /tmp/dnsmonster
[root@Home-Server dnsmonster]# go build -o dnsmonster ./cmd/dnsmonster
# github.com/gopacket/gopacket/pcap
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:52:17: undefined: pcapTPtr
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:64:10: undefined: pcapPkthdr
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:103:6: undefined: pcapBpfProgram
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:110:7: undefined: pcapPkthdr
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:268:33: undefined: pcapErrorActivated
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:269:33: undefined: pcapWarningPromisc
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:270:33: undefined: pcapErrorNoSuchDevice
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:271:33: undefined: pcapErrorDenied
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:750:14: undefined: pcapTPtr
/root/go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap.go:271:33: too many errors
+++++++++++++++++++++++++++++++++++++++++++
Brother, a long time ago I installed it in the same way and it got installed, but this time it is giving some error as I have mentioned above, maybe I am making some mistake from my side, I apologize for this but I searched for the whole day on this error and could not understand anything. So please suggest me.

**Comment by mosajjal** [comment]
Hi, 

CGO needs to be enabled to be able to compile with `libpcap` support. 

there is an option to compile without CGO using tags:

```bash
go build -tags nolibpcap ./...
```

**Comment by mosajjal** [comment]
closing... feel free to re-open if above comment didn't solve your issue.

**Comment by HesaMtiPu** [comment]
it's workings!!! Thanks @mosajjal
