### ISSUE TITLE
"IPv6 Packet Destination Top 20 Prefix" -- IPv6 addresses are incorrect

### ISSUE THREAD

**Issue by kansal15** [mosajjal/dnsmonster#25]
In "IPv6 Packet Destination Top 20 Prefix" panel, the IPv6 addresses are incorrect. 

e.g. in my panel ,it is showing random IPs. 

<img width="1370" alt="Screenshot 2022-03-22 at 11 38 28" src="https://user-images.githubusercontent.com/14325990/159418732-8e717b7b-82d6-404a-8693-60d4ce0a3023.png">

In csv.go page, the code for converting IPv6 address to decimal is --

`
SrcIP = binary.BigEndian.Uint64(d.SrcIP[:8]) //limitation of clickhouse-go doesn't let us go more than 64 bits for ipv6 at the moment
DstIP = binary.BigEndian.Uint64(d.DstIP[:8])
`

As per my understanding from above comment, clickhouse is not allowing more than 64 bits for a variable. Is there a way to show correct data on the panel ?

**Comment by mosajjal** [comment]
Hey there, I think I know what's the issue at least to some extent. in `csv.go` I can see the line is this:

```
DstIP = binary.BigEndian.Uint64(d.DstIP[:8])
```

but in `clickhouse.go`, it shows as this:

```
DstIP = binary.BigEndian.Uint64(d.DstIP[8:])
```

notice the `:` on the side of `8`. I need to do more testing. Unfortunately, clickhouse-go v2 still has a 64 bit int limitation so we just need to save either suffix or prefix which leads to these types of issues. I'll do more digging to see what's the best way to do it :)

**Comment by arjunnkn** [comment]
Clickhouse  do support uint128 and uint256 as well but the go language support is limited to uint64  so  dnsmonster code from the very beginning of the process of tapping / reading packets  and  sending them to clickhouse is  using uinnt64 for dealing with both Ipv6 SrcIP and DstIP 
so i think if we use "math/big" library to deal with it  while dealing with ipv6 addresses it may solve the issue

**Comment by mosajjal** [comment]
There are multiple ways to solve this. But in my opinion, the cleanest and most appropriate option is to change `SrcIP` and `DstIP` to `uint128` in `DNS_LOG`, and wait for [this issue](https://github.com/ClickHouse/clickhouse-go/issues/526) to be solved by ClickHouse.

**Comment by arjunnkn** [comment]
Yes that is necessary and uint128 is supported by clickhouse too but the thing is your go code is not dealing with ipv6 addresses that are above uint64 upper range and it dont support uintl128
So first that needed to he recified clickhouse will very well support all operations operation by simple changing uint64 to uint128

**Comment by mosajjal** [comment]
If the uint128 convo doesn't move, there's an option for us to move the IP address to `bytearray` type and deal with it that way. it'll be a bit of change for the dashboards and ClickHouse tables, but ultimately that might be a better option than lump all 128 bits of ipv6 as one giant `int`. Feel free to open a discussion topic about it so we can decide :)

**Comment by gingerwizard** [comment]
@mosajjal resolved in the https://github.com/ClickHouse/clickhouse-go/pull/568

**Comment by mosajjal** [comment]
btw @gingerwizard I'm waiting for the next release of clickhouse-go so I can upgrade the dependency and fix my side. Any ETA on that?

**Comment by gingerwizard** [comment]
@mosajjal we would like to get in JSON support at least in experimental. Its over run a little but I'm hoping within the next few days - although it depends on an upstream ClickHouse merge. If it doesn't happen by 10/06 ill cut a release.

**Comment by gingerwizard** [comment]
@mosajjal released. JSON PR is up but didn't make it so I cut a 2.0.15 release with bug fixes. Thanks again for raising the issue and helping to improve the driver.

**Comment by mosajjal** [comment]
thanks a lot @gingerwizard!

**Comment by mosajjal** [comment]
I've solved this issue in HEAD. Although it comes with a new table schema which also removes UUID and changes up the fields a little bit. @arjunnkn @kansal15 can you guys please test it out and let me know if everything works from your end so I can push it to a release.

**Comment by arjunnkn** [comment]
hi @mosajjal  will do it and share the positive results

**Comment by arjunnkn** [comment]
@mosajjal   hi , sorry  for late reply .. my team just confirmed thatwe are able to get IPV6 in dashboard now...thx
