### ISSUE TITLE
dnsmonster to clickhouse data replication

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#27]
First of all thank you for this amazing dnsmonster !!!
We have a cluster of three clickhouse nodes and our dns data is going through dnsmonster. But in the configuration of dnsmonster only one IP address of the clickhouse node is mentioned. The problem is that if our mentioned clickhouse node goes down, will our data replicate to the other cluster node?

**Comment by mosajjal** [comment]
Hi there. This feature is on the roadmap. It's already there for Splunk and Kafka. Hopefully next release will include this feature.

**Comment by mosajjal** [comment]
I made a small change that leverages builtin driver's support. Most likely I'll make a change to the way the Address is provided so we can have different credentials and TLS support for each address later on. Please let me know if the latest commit solves your issue. Happy to re-open if it doesn't
