### ISSUE TITLE
higher precision timestamps in clickhouse

### ISSUE THREAD

**Issue by zeromind** [mosajjal/dnsmonster#31]
It would be nice to have higher precision timestamps for the package's time in clickhouse.

The current DNS_Log table:
https://github.com/mosajjal/dnsmonster/blob/7ebb729d4655cd4f9ba85c800724f3c3313d049b/clickhouse/tables.sql#L1-L3

Am not sure why `IndexTime` is higher precision, but `PacketTime` is just seconds.

The PostgreSQL output uses `timestamp` for both
https://github.com/mosajjal/dnsmonster/blob/928d15f5243b37e9dae6a7f4b8ffab77bb65415a/output/postgres.go#L80
which is already higher precision, see https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-INPUT

Maybe the `PacketTime` column in clickhouse's `DNS_LOG` could be changed to the higher-resolution https://clickhouse.com/docs/en/sql-reference/data-types/datetime64 as well?

Just changing the data type for the column seems to work.

**Comment by mosajjal** [comment]
Hi there, 

you're right that this needs to change. I'm planning a major shift in ClickHouse tables when `MaterializedView` are out of Experimental phase and thoroughly tested. You can see a draft of it [here](https://github.com/mosajjal/dnsmonster/blob/7c2900a7d47b492fde7053438df9f9c32f36364d/clickhouse/tables-v2.sql).

Though these two changes are not necessarily connected, I would like to minimize the number of DB migrations from version to version.

**Comment by mosajjal** [comment]
added in the latest commit.
