### ISSUE TITLE
dnsmonser not sending packets from live interface to clickhouse

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#36]
### Hi !!
Hope You are doing Well.
I downloaded the latest dnsmonster(v0.9.5) binary from the release section . but dnsmonser not sending packets from live interface to clickhouse.
The error is given Below :--
[4515]: time="2022-10-07T18:11:53+05:30" level=warning msg="Error while executing batch: clickhouse [Append]:  clickhouse: expected 18 arguments, got 17"
-----------
but in your previous version binary like (v0.9.2 & v0.9.3) is working fine ...

kindly check and do the needful ....

Thanks !!!!

**Comment by mosajjal** [comment]
Hi. in `0.9.4` I removed the `uuid` column from the table. you can use [these instructions](https://clickhouse.com/docs/en/sql-reference/statements/alter/column/#drop-column) to remove your `uuid` column and that'll hopefully solve your issue. let me know if the problem still persists

**Comment by HesaMtiPu** [comment]
Okey !!! i will do it and share the positive results !!!

**Comment by HesaMtiPu** [comment]
> Hi. in `0.9.4` I removed the `uuid` column from the table. you can use [these instructions](https://clickhouse.com/docs/en/sql-reference/statements/alter/column/#drop-column) to remove your `uuid` column and that'll hopefully solve your issue. let me know if the problem still persists

**Comment by HesaMtiPu** [comment]
Thanks !!! Issue resloved !!!
