### ISSUE TITLE
SrcIP and DstIP in DNS_LOG table IPv4 addresses are incorrect

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#37]
![Screenshot from 2022-10-10 13-24-32](https://user-images.githubusercontent.com/75774130/194820661-6c3997e4-12a2-4d98-ac12-648fb3313c07.png)
----------------------------------
Kindly Suggest !!!

Thanks !!!

**Comment by mosajjal** [comment]
hey mate. 

all ipv4s are saved under ipv6 in this version. That'll allow both types of IPs to be saved in the db. are you having trouble querying the IPs or building graphs?

**Comment by HesaMtiPu** [comment]
hey !!!
it would be possible that when monster sends data from live packet to clickhouse then those ips should be correctly inserted in DNS_LOG??

**Comment by mosajjal** [comment]
https://en.wikipedia.org/wiki/IPv6_address#Transition_from_IPv4

hope this answers your question. if not, please re-open the issue
