### ISSUE TITLE
Potentially inaccurate packet count when reading from pcap file

### ISSUE THREAD

**Issue by danielloader** [mosajjal/dnsmonster#39]
![image](https://user-images.githubusercontent.com/933423/200147125-2c9f62fd-bd79-4457-a865-3ee87e335b7a.png)

Carrying on from the TCP race condition [issue](https://github.com/mosajjal/dnsmonster/issues/38).

Seems there's some discrepancies in the packet counting when loading a pcap file.

**Comment by mosajjal** [comment]
should be fixed in 3ee252dfad67d174f8125cb70c8551ba0513e526

**Comment by danielloader** [comment]
![image](https://user-images.githubusercontent.com/933423/200163769-d74e0b50-25a3-4a6b-a187-bdf823db4990.png)

Looks a lot healthier to me. Amazing work. On the one hand sorry I found two bugs, on the other hand you got to fix two bugs.


Thanks again for helping.

**Comment by mosajjal** [comment]
cheers mate. keep them coming :)

**Comment by danielloader** [comment]
Quite likely since next week the plan at work is to throw this all in kubernetes and scale it to breaking point. 😅

**Comment by mosajjal** [comment]
haha exciting! I'd be happy to feature your work in dnsmonster.dev as a case study for others too if it's a scaled use

**Comment by danielloader** [comment]
Any chance you can publish this as the latest tagged version?
