### ISSUE TITLE
Clickhouse datasource plugin showing as unsigned in grafana

### ISSUE THREAD

**Issue by anirudhmalhotra** [mosajjal/dnsmonster#4]
First of all I would like to say a big thank you for making this.

Everything gets installed fine, even getting the logs on clickhouse container when checked clickhouse-client, So that works brilliantly. However, while looking at the datasource in grafana. The local ch datasource doesn't load, tried adding new then noticed following error at the top
![Screenshot 2021-09-03 at 6 04 05 PM](https://user-images.githubusercontent.com/68842163/132006258-2a9b588b-415a-49a4-8f36-51b083347c67.png)

Tried changing the flag "allow_loading_unsigned_plugins" too, but the error is not going away. Clickhouse is not available in the list of datasources.

![Screenshot 2021-09-03 at 6 05 03 PM](https://user-images.githubusercontent.com/68842163/132006378-3acbee00-f796-484a-beda-a6716ac67b0e.png)

**Comment by mosajjal** [comment]
Hi there,

Appreciate the nice words :)

Can you please confirm which version of `dnamonster` are you using? I believe this was an issue before, not sure if the latest commit in the repo would have the same issue

**Comment by anirudhmalhotra** [comment]
Well I took the clone of the latest default main branch yesterday itself. My OS is ubuntu, I will check the version and update this comment once I have it.

**Comment by anirudhmalhotra** [comment]
I manually downloaded the plugin and extracted in plugin directory. It seems to work after that : )

**Comment by mosajjal** [comment]
ok cool. I'm considering making those folders sub-modules rather than copy pasting them in. makes it lighter as well. Will close this :)
