### ISSUE TITLE
File output supporting compression

### ISSUE THREAD

**Issue by danielloader** [mosajjal/dnsmonster#43]
Fairly simple question, would it be possible to have gzip compression options on the file output option?

Saves me having to use a file watcher on a directory to collect files and compress them prior to AWS S3 upload.

**Comment by mosajjal** [comment]
Hi there. S3 upload and file rotation/compression is on the roadmap. in the meantime, you can use the stdout output + a shell script to get the job done:

compression:
``` 
dnsmonster --stdoutoutputtype-1... | gzip |...
```

there is also a neat little project for both file rotation and compression of the old files [here](https://github.com/AutoScout24/stdin-rotate) that can temporarily solve your problem. This also addresses #42.

**Comment by mosajjal** [comment]
in the latest commit, I added a more comprehensive file output method with a directory and auto rotate/compress based on a `cron` schedule. S3/R2 output is also almost done :)
