### ISSUE TITLE
(Illegal type DateTime64(3) [ while pushing to view default.DNS_PROTOCOL] Latest Version(v0.9.7) DNS-Monster Showing Error while send data to Click-House

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#45]
`dnsmonster[8323]: time="2023-01-24T12:38:07+05:30" level=warning msg="Error while executing batch: code: 43, message: Illegal type DateTime64(3) of argument for aggregate function sumWithOverflow: while pushing to view default.DNS_PROTOCOL (f20ac7c5-9b15-4d2f-935f-7fb13614c12f)"

Kindly look into it !!!
Thanks !!!

**Comment by mosajjal** [comment]
Hi there. 

what's the version of ClickHouse and dnsmonster running

**Comment by HesaMtiPu** [comment]
Hey !!!
ClickHouse server version 22.12.3
dnsmonster version: v0.9.7

**Comment by mosajjal** [comment]
if you've upgraded dnsmonster from an older version, it's required to re-create the tables on clickhouse based on the new table schema. That's an unfortunate limitation of Clickhouse that the primary key of the table can't have it's typed modified.

**Comment by HesaMtiPu** [comment]
i did not upgrade dnsmonster from older version , just installed fresh both in new VM .

**Comment by mosajjal** [comment]
did you use the autobuild.sh script or re-created the folders. Also, if you're using Linux, you can use the build artifact from the latest commit [here](https://github.com/mosajjal/dnsmonster/suites/10635385276/artifacts/531091722)

**Comment by mosajjal** [comment]
also have a look on 0.9.9.

**Comment by HesaMtiPu** [comment]
Okey buddy !!!
I will check and share Positive Result.

**Comment by HesaMtiPu** [comment]
> also have a look on 0.9.9.
we need to re-create DNS_LOG table and DNS_PROTOCOL after installation of 0.9.9. ????
because problem is still persist.

**Comment by mosajjal** [comment]
unfortunately yes. it's a limitation of ClickHouse :(
