### ISSUE TITLE
Clickhouse Cloud

### ISSUE THREAD

**Issue by jcdmacleod** [mosajjal/dnsmonster#48]
I noticed that the scheme appears to have changed and I tried to apply that to the replicated example, but it is not working as expected.

**Comment by mosajjal** [comment]
Hi there. are you trying to upgrade from <0.9.9 to 0.9.9? if that's the case, you will have to re-create the tables to enable high-precision timestamp.

**Comment by jcdmacleod** [comment]
No, fresh 0.9.9 installation.

**Comment by mosajjal** [comment]
fixed in the latest commit's SQL tables. let me know if the problem still persists.
