### ISSUE TITLE
Decrypting DoT / DoH  sessions via passive DNS approach itself 

### ISSUE THREAD

**Issue by arjunnkn** [mosajjal/dnsmonster#59]
Hi ,
We want central logging by Extending DNSMonnster's capability . As in Case of SSL/TLS web traffic  we can decrypt a encrypted SSL/TLS session if we have access of server private key this is a very standard process in wireshark 

https://my.f5.com/manage/s/article/K19310681

can we work on DNS Monster to have this  feature to add optional priavte key in customised setup so that we can have decrypted DoT / DoH logs in table

**Comment by mosajjal** [comment]
Hi. I don't plan on adding this feature to dnsmonster. Main reasons behind this decision:
- TLS 1.3 and any new cipher suite that supports perfect forward secrecy won't work.
- All DNS/DOT/DOH implementations already have dnstap logging and dnsmonster has full support for it
