### ISSUE TITLE
Question regarding CNAME and Query response on Clickhouse

### ISSUE THREAD

**Issue by arvchristos** [mosajjal/dnsmonster#6]
Hello,
First, I would like to thank you for this excellent and useful project!
Regarding Clickhouse output, I am running a local stack and while monitoring my main interface, I cannot find CNAME queries in DNS_LOG table (Types are either 1 or 28 which are mapped to A and AAAA respectively). Is this an issue with my configuration or is this by default? 

Best,

**Comment by mosajjal** [comment]
Hi there,

Glad you enjoying dnsmonster :)

Qtype 5 should cover CNAME across both questions and responses of IPv4 and IPv6. Usually the behaviour would be an A/AAAA query being responded by type 5 and then another subsequent A query to the response FQDN will get to the final result. 

This should do it:

```sql
select * from DNS_LOG WHERE ResponseCode = 5 LIMIT 10
```

let me know if that answers your question.
