### ISSUE TITLE
Clickhouse flushing algo

### ISSUE THREAD

**Issue by mzealey** [mosajjal/dnsmonster#61]
It seems like the default config is just batching clickhouse output and only writing when the batch is full, which is a bit confusing - changing to using 1s flush interval makes the flushes work correctly in low-quantity testing.

May I suggest that you have a flush algorithm that flushes EITHER when flush interval OR batch size is reached as that is the standard way to do things? And that flush interval is set to eg 5s as default?

**Comment by mosajjal** [comment]
I agree it's a bit confusing but it's there for a reason. I used to have the algorithm you're mentioning. meaning it did batching but no matter if the batch is full or not, flush would happen in intervals. but the performance of that hit a ceiling after 200k request per second. 

At the moment my assumption is when you set up dnsmonster you know if you're in a low-volume env (flush interval) or a high-volume env (batch count).
