### ISSUE TITLE
Not logged all data from Interface Device

### ISSUE THREAD

**Issue by HesaMtiPu** [mosajjal/dnsmonster#72]
Hi ..
we are observing a issue in monster while logging data to click-house from monster.
we have two standalone VMs in same location and configured monster with latest version.
but in one VMs data are being logged less than second VMs.
Supoose we have 100 packets of data then one VMs loogged 80 packets and second VMs logged 30 Packets.
I suppose that both VMs should logged full 100 of packets without any loss.

**Comment by mosajjal** [comment]
Hi. I guess it could be because of your batch size or batch delay settings. change your batch size to 5 and see if that helps with the loss percentge as a test.

**Comment by HesaMtiPu** [comment]
@mosajjal !!! Loss percentage has come down but full data is not coming yet.
Still the capture and output are not equal.

**Comment by wthahaha** [comment]
2023-11-01T22:21:03+08:00 metrics: {"clickhouseFailed":{"count":0},"clickhouseSentToOutput":{"count":294700000},"clickhouseSkipped":{"count":0},"packetLossPercent":{"value":9.000145739825104},"packetsCaptured":{"value":530609941},"packetsDropped":{"value":47755668},"packetsDuplicate":{"count":0},"packetsOverRatio":{"count":0}},
This is my log,packetLossPercent is 9%, is there any good idea to reduce packetLossPercent ? Thank you. @mosajjal @HesaMtiPu

**Comment by HesaMtiPu** [comment]
@wthahaha  2023-11-03T11:03:10+05:30 metrics: {"clickhouseFailed":{"count":0},"clickhouseSentToOutput":{"count":15937805893},"clickhouseSkipped":{"count":0},"packetLossPercent":{"value":0},"packetsCaptured":{"value":18509282722},"packetsDropped":{"value":0},"packetsDuplicate":{"count":0},"packetsOverRatio":{"count":0}}

**Comment by mosajjal** [comment]
what is your QPS @wthahaha? have you looked at your CPU/RAM usage while running dnsmonster?

**Comment by HesaMtiPu** [comment]
metrics: {"clickhouseFailed":{"count":0},"clickhouseSentToOutput":{"count":17515},"clickhouseSkipped":{"count":0},"packetLossPercent":{"value":0},"packetsCaptured":{"value":17515},"packetsDropped":{"value":0},"packetsInvalid":{"value":0},"stdoutSentToOutput":{"count":17515},"stdoutSkipped":{"count":0}}
@wthahaha 
PacketLossPercent is 0 and has been tested with data logged with DNStap and a small set of data.
