### ISSUE TITLE
can dnsmonster handle 5,000,000 QPS?

### ISSUE THREAD

**Issue by wthahaha** [mosajjal/dnsmonster#82]
Hi,,
Can dnsmonster handle 5,000,000 QPS? We have a passive server about receive DNS traffic,  and we want analyze the traffic data by dnsmonster, I'm not sure if it's a best way？
bellow is my server network info：
![image](https://github.com/mosajjal/dnsmonster/assets/19517430/ed11c29b-0613-4570-b398-9cb3276d9fc7)

**Comment by mosajjal** [comment]
Hi. I've never tested `dnsmonster` for traffic bigger than 500k QPS. Happy to work with you to understand the bottlenecks and potentially rewrite to make it more scalable.

**Comment by wthahaha** [comment]
Oh, sure, i will share my explore.

**Comment by wthahaha** [comment]
I have a  clickhouse  problem, when I execute bellow command, but the data can't insert to clickhouse, There is no error output. could you help me? thanks

./dnsmonster --devName enp125s0f0 --packethandlercount=8 --useafpacket --clickhouseaddress=x.x.x.x:9000 --clickhouseusername=xxx--clickhousepassword='xxx' --clickhousedatabase=xxx--clickhouseoutputtype=1

**Comment by mosajjal** [comment]
I suggest you start with the `stdoutoutput` and push the results to `/dev/null` first, to factor out disk i/o and clickhouse performance. after that tuning is complete and you could confirm if in fact 5M QPS can be processed by `dnsmonster`, we can focus on clickhouse.
