### ISSUE TITLE
pcap by stdin?

### ISSUE THREAD

**Issue by dstruck** [mosajjal/dnsmonster#9]
Is it possible to pipe pcap data to dnsmonster? Sometimes a network stream needs first to be decapsulated.

Something like `pcap.OpenOfflineFile(os.Stdin)`?

**Comment by mosajjal** [comment]
Hi there,

I work around this by using the following:

```
cat /path/to/pcap/file | dnsmonster --pcapFile=/dev/stdin --stdoutOutputType=1 
```

let me know if that solves your issue.

**Comment by dstruck** [comment]
Indeed this solved my issue.

Thank you :-)
